# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRequerimiento', models.DateField(default=datetime.date.today, max_length=100)),
                ('requerimiento', models.TextField()),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('razonProblema', models.TextField()),
                ('fechaSolucion', models.DateField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('P', 'En proceso'), ('T', 'Terminado')], max_length=1)),
            ],
        ),
    ]
